### ISSUE TITLE
IE11 评论回复提示 点击后会提示页面丢失

### ISSUE THREAD

**Issue by hujunyuan8058** [shen100/mili#232]
IE11 评论回复提示 点击后会提示页面丢失

![x8xmko da6_g kd5zr vmh](https://user-images.githubusercontent.com/37411247/37553084-983b6cc6-29b8-11e8-9590-f99cfc16fde8.png)
![h 5mxsms s6 2m0pw_94uql](https://user-images.githubusercontent.com/37411247/37553085-9c0677e2-29b8-11e8-8881-9c16e4134aeb.png)

**Comment by shen100** [comment]
重构了，新版已发布
https://www.golang123.com
