### ISSUE TITLE
IE11 在线图书 目录不显示

### ISSUE THREAD

**Issue by hujunyuan8058** [shen100/mili#234]
https://www.golang123.com/book/10
![s j 8r4 fzbm0i1v _ 1sc1](https://user-images.githubusercontent.com/37411247/37554286-17a74e66-29ce-11e8-8797-91c10a1fe27e.png)

**Comment by hujunyuan8058** [comment]
IE11 在线图书  所有目录都不显示。
如：https://www.golang123.com/book/9
https://www.golang123.com/book/12
https://www.golang123.com/book/15

**Comment by shen100** [comment]
重构了，新版已发布
https://www.golang123.com
