### ISSUE TITLE
IE11升级后 首次登陆，登陆页面“登陆按钮” 不显示

### ISSUE THREAD

**Issue by hujunyuan8058** [shen100/mili#246]
IE11升级后 首次登陆，登陆页面“登陆按钮” 不显示，关闭浏览器重启后又是正常的。

![lexmo b0vg is oq_bh 2](https://user-images.githubusercontent.com/37411247/38074299-d8a436b2-331d-11e8-8010-76ac135cea6f.png)

**Comment by shen100** [comment]
重构了， 新版已发布
https://www.golang123.com
