### ISSUE TITLE
cookie无法读取

### ISSUE THREAD

**Issue by zhang8h** [shen100/mili#269]
获取cookie一直报错：

`http: named cookie not present`

**Comment by shen100** [comment]
请详细描述问题

**Comment by zhang8h** [comment]
@shen100  同时支持http 和https吗

**Comment by danmingyang** [comment]
我也是，一直搞不懂，我是用的https，但是nginx转发到了http://127.0.0.1:8000,不知道是什么因为的

**Comment by zhang8h** [comment]
我换成其他形式坐等了验证了，他是把前后端放一个域名下了

**Comment by danmingyang** [comment]
我刚验证了，如果用楼主的nginx配置，前端和服务器在一个服务器上，没有这个错误了

**Comment by shen100** [comment]
重构了，新版已发布
https://www.golang123.com
