### ISSUE TITLE
移动端是怎么自动跳转的？

### ISSUE THREAD

**Issue by aiaa5505** [shen100/mili#271]
移动端是怎么自动跳转的？

**Comment by shen100** [comment]
什么意思？请详细描述

**Comment by zinwalin** [comment]
> 什么意思？请详细描述

检测到手机设备, 转到m.golang123.com

**Comment by im-here** [comment]
请问是如何实现检测到手机设备, 转到m.golang123.com？代码里没看到有agent的判断，难道是在Nginx里实现的吗？但是Nginx的配置文件里也没有呢

**Comment by shen100** [comment]
跳转是判断浏览器的user agent，已重构，新版已发布
https://www.golang123.com
