### ISSUE TITLE
请问怎么发表带颜色效果的文字

### ISSUE THREAD

**Issue by xrfinbupt** [shen100/mili#283]
`<font color="red">知道了</font> `

不管用？

**Comment by xrfinbupt** [comment]
<font color=red>知道了</font>

**Comment by xrfinbupt** [comment]
<span style="color:red;">这是比font标签更好的方式。可以试试。</span>

**Comment by shen100** [comment]
@xrfinbupt  现在写文章时，同时支持markdown编辑器，和富文本编辑器
