### ISSUE TITLE
执行npm run dev报错

### ISSUE THREAD

**Issue by zuochangqin** [shen100/mili#285]
执行:npm run dev报以下错误: 
 ERROR  Failed to compile with 5 errors                                                                                                                                                                                    22:23:41

This dependency was not found:

* ~/config in ./config/adminAPIConfig.js, ./config/apiConfig.js and 3 others

To install it, you can run: npm install --save ~/config

这个是nodejs的问题吗?

**Comment by zhangweilun** [comment]
我也是这个问题

**Comment by liliang8858** [comment]
Module parse failed: Unexpected token (5:39) You may need an appropriate loader to handle this file type. | import { interopDefault } from './utils'; | > const _1d8113b0 = () => interopDefault(import('..\\pages\\about.vue' | /* webpackChunkName: "pages_about" */ | ));

我是这个问题

**Comment by liliang8858** [comment]
使用  yarn 安装了一遍  好了

**Comment by shen100** [comment]
已重构，新版已发布
https://www.golang123.com/
