### ISSUE TITLE
关于新架构的一点建议

### ISSUE THREAD

**Issue by zuohuadong** [shen100/mili#286]
听到 golang123 要用nest.js 重构，感觉很兴奋。

我们目前技术栈  vue  angular  ionic   nest.js  graphql  typeorm ...

由于nest.js 参考了 angular，所以这俩也十分相像，精简技术栈，倒是可以考虑 angular (material2) + nestjs  

SEO问题可以参考： https://angular.cn/guide/universal

后台，我们目前在维护一套框架：https://github.com/notadd/ng-notadd

其他一些问题也可以一起探讨～

除了日常的一些BUG修复之外，我们也可以提供设计～

**Comment by shen100** [comment]
感谢建议，新版已发布
https://www.golang123.com
