### ISSUE TITLE
go run main.go  各种问题

### ISSUE THREAD

**Issue by shiguodong** [shen100/mili#290]
在运行命令的时候 出现

main.go:10:2: cannot find package "github.com/shen100/golang123/config" in any of:
	/Users/guodongshi/go/src/github.com/web/golang123/vendor/github.com/shen100/golang123/config (vendor tree)
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/shen100/golang123/config (from $GOROOT)
	/Users/guodongshi/go/src/github.com/shen100/golang123/config (from $GOPATH)
main.go:11:2: cannot find package "github.com/shen100/golang123/cron" in any of:
	/Users/guodongshi/go/src/github.com/web/golang123/vendor/github.com/shen100/golang123/cron (vendor tree)
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/shen100/golang123/cron (from $GOROOT)
	/Users/guodongshi/go/src/github.com/shen100/golang123/cron (from $GOPATH)
main.go:12:2: cannot find package "github.com/shen100/golang123/middleware"

**Comment by lpzgithub** [comment]
@shiguodong 你尝试下载dep，然后使用dep ensure下载相关依赖了吗？ 详细看README。

**Comment by shen100** [comment]
新版本已发布了哦
https://www.golang123.com

**Comment by Butonix** [comment]
> 新版本已发布了哦
> https://www.golang123.com

Where's the source code?))
