### ISSUE TITLE
npm run dev nuxt:build报错

### ISSUE THREAD

**Issue by daiSky88** [shen100/mili#301]
> golang123-pc@0.1.1 dev /root/go/src/github.com/shen100/golang123/website
> nuxt

  nuxt:build App root: /root/go/src/github.com/shen100/golang123/website +0ms
  nuxt:build Generating /root/go/src/github.com/shen100/golang123/website/.nuxt files... +2ms
  nuxt:build Generating files... +17ms
  nuxt:build Generating routes... +26ms
  nuxt:build Building files... +83ms
  nuxt:build Adding webpack middleware... +255ms
  build [==================  ] 90%已杀死

**Comment by shen100** [comment]
新版已发布，去掉了nuxt
https://www.golang123.com
