### ISSUE TITLE
请问前端文件用npm run build 打包后。怎么没有生成dist文件。如何发布到nginx中

### ISSUE THREAD

**Issue by ssuhvs** [shen100/mili#305]
请问前端文件用npm run build 打包后。怎么没有生成dist文件。如何发布到nginx中

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by shen100** [comment]
重构了，新版已发布
https://www.golang123.com
