### ISSUE TITLE
新版问题汇总

### ISSUE THREAD

**Issue by shen100** [shen100/mili#306]
1 makrdown编辑器, 输入回车时，应该换行，现在是两个字符后再换行
![image](https://user-images.githubusercontent.com/2443162/68522040-e0c31580-02e1-11ea-89b6-c4ae768cbe20.png)
2 重构makrdown编辑器, 去掉 simplemde-markdown-editor， 直接用 marked

**Comment by zinwalin** [comment]
沸点里， 上传图片失败，并且无任何提示。

**Comment by zinwalin** [comment]
回复消息时，需要手动刷新网页才能看到自己发出的消息。
