### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by Butonix** [shen100/mili#315]
**npm start**
> ts-node -r tsconfig-paths/register src/main.ts
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mili@0.11.0 start: `ts-node -r tsconfig-paths/register src/main.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mili@0.11.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**/pc npm start**
```
ERROR in ./js/components/common/sidemenu/SideMenu.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader??ref--2-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--2-3!./node_modules/vue-loader/lib??vue-loader-options!./js/components/common/sidemenu/SideMenu.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
```

**node dist/main.js**
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/Users/ckatala/Downloads/mili-master/dist/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by shen100** [comment]
1. 前端有个报错， Error: Cannot find module 'node-sass'，  你npm install 安装依赖的模块了吗
2. 后端，按照文档中的配置，使用vscode运行

**Comment by Butonix** [comment]
> 1. 前端有个报错， Error: Cannot find module 'node-sass'，  你npm install 安装依赖的模块了吗
> 2. 后端，按照文档中的配置，使用vscode运行

This shit doesn't work
