### ISSUE TITLE
后端既然使用 nest.js ，前端可以使用 angular ，能共享代码

### ISSUE THREAD

**Issue by zuohuadong** [shen100/mili#316]
参考：https://github.com/nstudio/xplat
所生成的目录结构。

且 angular 跟 nest.js 思想一致，学 nest.js 再学点 css， angular 也可以搞了

**Comment by shen100** [comment]
@zuohuadong   之前已经用vue写了很多代码了, 换成其他的代价太大了

**Comment by zuohuadong** [comment]
@shen100  后面维护起来麻烦。 比如一些验证，前端需要验证，后端也需要，用 xplat 这种结构，就可以前后端共享这部分代码。  或者是一些库的共享，后面开发会越来越简单。
